In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df_plazas = pd.read_excel('Plazas.xlsx')
df_plazas.head(5)

,Fecha Origen,Nombre,Telefono,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo solicitud de credito?,¿Por que no se ha formalizado la compra?,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,2025-05-06 18:30:00,Alejandro Fernandez,NaN,AION,NANCY OLASCOAGA CASTILLO,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Recibe recurso a finales de junio, proyección ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-05-06 18:00:00,David Israel,NaN,EMKOO,JOSE EDUARDO PARADA DURAN,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Finalizado,Si hay seguimiento,Dejo de contestar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-05-06 13:50:00,Rosendo Ceron,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-05-06 13:47:00,Fausto Ochoa Martinez,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-05-06 13:43:00,Brigida Lara Perez,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
valores_nulos = df_plazas.isnull().sum()
valores_nulos

Fecha Origen                                1048272
Nombre                                      1048271
Telefono                                    1048574
Producto                                    1048271
Asesor                                      1048271
Origen                                      1048271
Seguimiento                                       7
Cita efetiva                                     10
PDM                                              11
SDC                                              11
Estatus                                           7
¿Por que no hay seguimiento?                1048375
¿Por que no ha visitado la agencia?         1048405
¿Por que no hubo prueba de manejo ?         1048546
¿Por que no hubo solicitud de credito?      1048547
¿Por que no se ha formalizado la compra?    1048560
Unnamed: 16                                 1048550
Unnamed: 17                                 1048574
Unnamed: 18                                 1048574
Unnamed: 19                                 1048573
dtype: int64

In [5]:
valores_nulos = df_plazas.isnull().sum().sum()
valores_nulos

np.int64(15726680)

In [6]:
df_plazas2 = df_plazas.copy()

In [7]:
print(df_plazas2.columns)

Index(['Fecha Origen', 'Nombre', 'Telefono', 'Producto', 'Asesor', 'Origen',
       'Seguimiento', 'Cita efetiva ', 'PDM', 'SDC', 'Estatus',
       '¿Por que no hay seguimiento?', '¿Por que no ha visitado la agencia?',
       '¿Por que no hubo prueba de manejo ?',
       '¿Por que no hubo solicitud de credito?',
       '¿Por que no se ha formalizado la compra?', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19'],
      dtype='str')

In [8]:
df_plazas2 = df_plazas2.drop(['¿Por que no hubo prueba de manejo ?', '¿Por que no hubo solicitud de credito?', '¿Por que no se ha formalizado la compra?'], axis = 1)
df_plazas2

,Fecha Origen,Nombre,Telefono,Producto,Asesor,Origen,Seguimiento,Cita efetiva,PDM,SDC,Estatus,¿Por que no hay seguimiento?,¿Por que no ha visitado la agencia?,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,2025-05-06 18:30:00,Alejandro Fernandez,NaN,AION,NANCY OLASCOAGA CASTILLO,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Recibe recurso a finales de junio, proyección ...",NaN,NaN,NaN,NaN
1,2025-05-06 18:00:00,David Israel,NaN,EMKOO,JOSE EDUARDO PARADA DURAN,PLAZA ANGELOPOLIS,1.0,0.0,0.0,0.0,Finalizado,Si hay seguimiento,Dejo de contestar,NaN,NaN,NaN,NaN
2,2025-05-06 13:50:00,Rosendo Ceron,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN
3,2025-05-06 13:47:00,Fausto Ochoa Martinez,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN
4,2025-05-06 13:43:00,Brigida Lara Perez,NaN,EMZOOM,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,1.0,0.0,0.0,0.0,Contactado,Si hay seguimiento,"Ya se hizo la invitación, eperando respuesta",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048569,2025-06-09 15:30:00,Miguel Fernandez,NaN,GS8,PEDRO ANTONIO CINTO DE GANTE,PLAZA ANGELOPOLIS,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN
1048570,2025-06-09 13:15:00,Luis,NaN,EMZOOM,SERGIO RAYMUNDO VAZQUEZ SANCHEZ,GALERIAS TLAXCALA,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN
1048571,2025-06-09 13:14:00,Rolando Manrique,NaN,EMZOOM,SERGIO RAYMUNDO VAZQUEZ SANCHEZ,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN
1048572,2025-06-09 12:50:00,Odilia Cuamatzi Bautista,NaN,GS8,MAURICIO ALFREDO VAZQUEZ FARFAN,Gran Patio Tlaxcala,0.0,0.0,0.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN
1048573,2025-05-24 12:19:22,Raul Jimenez,NaN,EMZOOM,RICARDO SILVA HERAS,PLAZA ANGELOPOLIS,1.0,NaN,NaN,NaN,Contactado,Si hay seguimiento,Esta preautorizado,NaN,NaN,NaN,NaN