In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Citas_Digital_Filtrado.csv')
data.head(5)

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...

In [3]:
#Identificar valores nulos por columna
valores_nulos = data.isnull().sum()
valores_nulos

BDC                                          16
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [4]:
#Identificar valores nulos en todo el dataframe
valores_nulos = data.isnull().sum().sum()
valores_nulos

np.int64(3557)

In [5]:
## Eliminar columnas que no aportan
#La columna 'Unnamed: 15' es un residuo del archivo original (sin nombre y casi vacia), no aporta datos
#axis = 1 para columnas
data1 = data.drop(['Unnamed: 15'], axis=1)
data1

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,Ana,2026-07-22,Maira Escalante,NaN,Activo,0.8,1.0,1.0,0.0,Pedro Antonio,NaN,NaN,NaN,NaN,NaN
672,Ignacio,2026-07-22,Zaira Macip,NaN,Activo,0.5,0.0,0.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN
673,Ignacio,2026-07-27,Julio Hernandez,NaN,Activo,0.5,1.0,0.0,0.0,Victor,NaN,NaN,NaN,NaN,NaN
674,Ignacio,2026-07-24,Xhunaxhi Vicente,NaN,Activo,1,1.0,1.0,1.0,Ignacio,NaN,NaN,NaN,NaN,NaN
675,Ignacio,2026-07-29,DR Jairo Rodriguez Farias,NaN,Activo,1,1.0,1.0,1.0,Victor,NaN,NaN,NaN,NaN,NaN

In [6]:
#Corroboramos valores nulos
valores_nulos = data1.isnull().sum()
valores_nulos

BDC                                          16
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [7]:
##Metodos de sustitución de valores nulos
#Realizamos una copia del dataframe
data2 = data1.copy()

In [8]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos por un string en concreto (columna categorica con pocos nulos)
data2["BDC "] = data2["BDC "].fillna("Sin dato")

In [10]:
#Segundo método de sustitución de valores nulos
#Sustituir valores nulos por un string en concreto
data2["Telefono "] = data2["Telefono "].fillna("Sin telefono")

In [12]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un string en concreto 
data2["Fecha"] = data2["Fecha"].fillna("Sin fecha registrada")

In [13]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en concreto (no se puede inventar el nombre del cliente)
data2["Nombre Cliente "] = data2["Nombre Cliente "].fillna("Desconocido")

In [14]:
#Quinto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia adelante "forward fill" ("ffill")
#Filtro por columnas
data2["Estatus de Lead"] = data2["Estatus de Lead"].ffill()

In [15]:
#Sexto método de sustitución de valores nulos
#Sustituir valores nulos por valores no nulos hacia atrás "backward fill" ("bfill")
#Filtro por columnas
data2["Asesor Asignado"] = data2["Asesor Asignado"].bfill()

In [16]:
#Septimo método de sustitución de valores nulos
#La columna tiene datos sucios (texto suelto y simbolos de porcentaje mal escritos), los limpiamos primero
data2["Potencial de compra"] = data2["Potencial de compra"].replace({
    "Ventas ": np.nan,
    "80%%": "0.8",
    "8'%": "0.8",
    "80&": "0.8"
})

#Convertimos la columna a numerica (venia como texto) y sustituimos los nulos con el promedio
data2["Potencial de compra"] = data2["Potencial de compra"].astype(float)
data2["Potencial de compra"] = data2["Potencial de compra"].fillna(round(data2["Potencial de compra"].mean(), 2))

In [17]:
#Octavo método de sustitución de valores nulos
#Sustituir valores nulos por un valor numerico en concreto (PDM, SDC y Venta son columnas de 0 y 1)
data2["PDM"] = data2["PDM"].fillna(0)
data2["SDC"] = data2["SDC"].fillna(0)
data2["Venta"] = data2["Venta"].fillna(0)

In [18]:
#Noveno método de sustitución de valores nulos
#Sustituir valores nulos por un string en concreto ("No aplica" ya que el nulo significa que esa pregunta no correspondia al cliente)
preguntas = ['¿Por que no ha visitado la agencia?',
             '¿Por que no hay solicitud de credito?',
             '¿Por que no hubo prueba de manejo ?',
             '¿Por que no hubo proceso wow?',
             '¿Por que se asigno antes de vistar piso?']

data2[preguntas] = data2[preguntas].fillna("No aplica")

In [19]:
#Corroboramos valores nulos en todo el dataframe
valores_nulos = data2.isnull().sum().sum()
valores_nulos

np.int64(0)

In [21]:

##Metodo de eliminación de valores nulos
# #Identificar valores nulos por columna
valores_nulos = data1.isnull().sum()
valores_nulos

BDC                                          16
Fecha                                       601
Nombre Cliente                               21
Telefono                                    674
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [22]:
#Realizamos una copia del dataframe
data3 = data1.copy()

In [23]:
#Eliminamos filas con nulos
#No se agrega nada para eliminar filas y 1 para eliminar columnas
data3 = data1.dropna()
data3

Empty DataFrame
Columns: [BDC , Fecha, Nombre Cliente , Telefono , Estatus de Lead, Potencial de compra, PDM, SDC, Venta, Asesor Asignado, ¿Por que no ha visitado la agencia?, ¿Por que no hay solicitud de credito?, ¿Por que no hubo prueba de manejo ?, ¿Por que no hubo proceso wow?, ¿Por que se asigno antes de vistar piso?]
Index: []

In [24]:
#Identificar valores nulos por columna
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Telefono                                    0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         0
SDC                                         0
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
dtype: int64

In [25]:
data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       676 non-null    str
 1   Fecha                                     676 non-null    str
 2   Nombre Cliente                            676 non-null    str
 3   Telefono                                  676 non-null    str
 4   Estatus de Lead                           676 non-null    str
 5   Potencial de compra                       676 non-null    float64
 6   PDM                                       676 non-null    float64
 7   SDC                                       676 non-null    float64
 8   Venta                                     676 non-null    float64
 9   Asesor Asignado                           676 non-null    str
 10  ¿Por que no ha visitado la agencia?       676 non-null    str
 11  ¿Por que no hay solicitud de credito?     676 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       676 non-null    str
 13  ¿Por que no hubo proceso wow?             676 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  676 non-null    str
dtypes: float64(4), str(11)
memory usage: 79.3 KB

In [26]:
data3.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       0 non-null      str
 1   Fecha                                     0 non-null      str
 2   Nombre Cliente                            0 non-null      str
 3   Telefono                                  0 non-null      str
 4   Estatus de Lead                           0 non-null      str
 5   Potencial de compra                       0 non-null      str
 6   PDM                                       0 non-null      float64
 7   SDC                                       0 non-null      float64
 8   Venta                                     0 non-null      float64
 9   Asesor Asignado                           0 non-null      str
 10  ¿Por que no ha visitado la agencia?       0 non-null      str
 11  ¿Por que no hay solicitud de credito?     0 non-null      str
 12  ¿Por que no hubo prueba de manejo ?       0 non-null      str
 13  ¿Por que no hubo proceso wow?             0 non-null      str
 14  ¿Por que se asigno antes de vistar piso?  0 non-null      str
dtypes: float64(3), str(12)
memory usage: 132.0 bytes

In [27]:
#Convertir DataFrame a CSV (usamos data2, el de sustitucion, porque conserva todas las filas)
data2.to_csv("Citas_Digital_sin_nulos.csv", index=False)